# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50d24c28388da4712f8c9e5618af4095"
name = "Arrively"
application_url = "https://conceptual-iowa-medicine-documentation.trycloudflare.com/app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "win-win-ccae-dev.myshopify.com"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://conceptual-iowa-medicine-documentation.trycloudflare.com/auth/callback",
  "https://conceptual-iowa-medicine-documentation.trycloudflare.com/auth/shopify/callback",
  "https://conceptual-iowa-medicine-documentation.trycloudflare.com/shopify/auth/callback"
]

[pos]
embedded = false
